const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_EMAIL_BACKEND: 'CLEAR_EMAIL_BACKEND',
  CLEAR_PASSWORD_BACKEND: 'CLEAR_PASSWORD_BACKEND',
  CLEAR_ERROR: 'CLEAR_ERROR'
};

const ACCOUNT = {
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER'
};

const POST = {
  SET_POST: 'SET_POST',
  EXP_ADD_POST: 'EXP_ADD_POST',
  ADD_POST: 'ADD_POST',
  EXP_UPDATE_POST: 'EXP_UPDATE_POST',
  UPDATE_POST: 'UPDATE_POST',
  EXP_DELETE_ONE_POST: 'EXP_DELETE_ONE_POST',
  DELETE_ONE_POST: 'DELETE_ONE_POST',
  EXP_DELETE_ALL_POSTS: 'EXP_DELETE_ALL_POSTS',
  DELETE_ALL_POSTS: 'DELETE_ALL_POSTS'
}

export { ERRORS, ACCOUNT, POST }