const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_EMAIL_BACKEND: 'CLEAR_EMAIL_BACKEND',
  CLEAR_PASSWORD_BACKEND: 'CLEAR_PASSWORD_BACKEND'
};

const ACCOUNT = {
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER'
};

const POST = {
  ADD_POST: 'ADD_POST',
  UPDATE_POST: 'UPDATE_POST',
  DELETE_POST: 'DELETE_POST'
}

export { ERRORS, ACCOUNT, POST }