const ERRORS = {
  ERROR: 'ERROR',
  CLEAR_EMAIL_BACKEND: 'CLEAR_EMAIL_BACKEND',
  CLEAR_PASSWORD_BACKEND: 'CLEAR_PASSWORD_BACKEND'
};

const ACCOUNT = {
  REGISTER_USER: 'REGISTER_USER',
  SIGN_IN_USER: 'SIGN_IN_USER'
};

export { ERRORS, ACCOUNT }